# Generated by Django 5.0.1 on 2024-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('brown', 'Brown'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Double Extra Large'), ('xxxl', 'Triple Extra Large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('brown', 'Brown'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Double Extra Large'), ('xxxl', 'Triple Extra Large')], max_length=255),
        ),
    ]
